/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) shark_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s2[21] = {8, 2, 0, 8, 16, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* shark_model_expl_vde_forw:(i0[8],i1[8x8],i2[8x2],i3[2],i4[12])->(o0[8],o1[8x8],o2[8x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  a4=arg[0]? arg[0][4] : 0;
  a5=sin(a1);
  a6=(a4*a5);
  a3=(a3-a6);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a6=(a0*a3);
  a7=cos(a1);
  a8=(a4*a7);
  a6=(a6+a8);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a6;
  a8=arg[0]? arg[0][6] : 0;
  a9=arg[0]? arg[0][7] : 0;
  a10=(a8+a9);
  a11=55.;
  a12=(a11*a6);
  a13=(a12*a4);
  a10=(a10+a13);
  a13=arg[4]? arg[4][1] : 0;
  a14=(a13*a6);
  a15=(a14*a4);
  a10=(a10+a15);
  a15=arg[4]? arg[4][3] : 0;
  a16=(a15*a0);
  a10=(a10+a16);
  a16=arg[4]? arg[4][6] : 0;
  a17=casadi_fabs(a0);
  a17=(a16*a17);
  a18=(a17*a0);
  a10=(a10+a18);
  a18=arg[4]? arg[4][9] : 0;
  a10=(a10+a18);
  a18=arg[4]? arg[4][0] : 0;
  a19=(a11+a18);
  a10=(a10/a19);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[4]? arg[4][4] : 0;
  a20=(a10*a4);
  a21=(a11*a6);
  a22=(a21*a0);
  a23=(a18*a6);
  a24=(a23*a0);
  a22=(a22+a24);
  a20=(a20-a22);
  a22=arg[4]? arg[4][7] : 0;
  a24=casadi_fabs(a4);
  a24=(a22*a24);
  a25=(a24*a4);
  a20=(a20+a25);
  a25=arg[4]? arg[4][10] : 0;
  a20=(a20+a25);
  a25=(a11+a13);
  a20=(a20/a25);
  if (res[0]!=0) res[0][4]=a20;
  a20=(a18*a0);
  a26=(a20*a4);
  a27=-3.9500000000000002e-01;
  a8=(a27*a8);
  a28=3.9500000000000002e-01;
  a9=(a28*a9);
  a8=(a8+a9);
  a9=(a13*a0);
  a29=(a9*a4);
  a8=(a8+a29);
  a26=(a26-a8);
  a8=arg[4]? arg[4][5] : 0;
  a29=(a8*a6);
  a26=(a26+a29);
  a29=arg[4]? arg[4][8] : 0;
  a30=casadi_fabs(a6);
  a30=(a29*a30);
  a31=(a30*a6);
  a26=(a26+a31);
  a31=arg[4]? arg[4][11] : 0;
  a26=(a26+a31);
  a31=1.5100000000000000e+01;
  a32=arg[4]? arg[4][2] : 0;
  a31=(a31+a32);
  a26=(a26/a31);
  if (res[0]!=0) res[0][5]=a26;
  a26=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][6]=a26;
  a26=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][7]=a26;
  a26=arg[1]? arg[1][3] : 0;
  a32=(a2*a26);
  a33=sin(a1);
  a34=arg[1]? arg[1][2] : 0;
  a35=(a33*a34);
  a35=(a0*a35);
  a32=(a32-a35);
  a35=arg[1]? arg[1][4] : 0;
  a36=(a5*a35);
  a37=cos(a1);
  a38=(a37*a34);
  a38=(a4*a38);
  a36=(a36+a38);
  a32=(a32-a36);
  if (res[1]!=0) res[1][0]=a32;
  a32=(a3*a26);
  a36=cos(a1);
  a38=(a36*a34);
  a38=(a0*a38);
  a32=(a32+a38);
  a38=(a7*a35);
  a39=sin(a1);
  a34=(a39*a34);
  a34=(a4*a34);
  a38=(a38-a34);
  a32=(a32+a38);
  if (res[1]!=0) res[1][1]=a32;
  a32=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a32;
  a38=arg[1]? arg[1][6] : 0;
  a34=arg[1]? arg[1][7] : 0;
  a40=(a38+a34);
  a41=(a11*a32);
  a41=(a4*a41);
  a42=(a12*a35);
  a41=(a41+a42);
  a40=(a40+a41);
  a41=(a13*a32);
  a41=(a4*a41);
  a42=(a14*a35);
  a41=(a41+a42);
  a40=(a40+a41);
  a41=(a15*a26);
  a40=(a40+a41);
  a41=casadi_sign(a0);
  a42=(a41*a26);
  a42=(a16*a42);
  a42=(a0*a42);
  a43=(a17*a26);
  a42=(a42+a43);
  a40=(a40+a42);
  a40=(a40/a19);
  if (res[1]!=0) res[1][3]=a40;
  a40=(a10*a35);
  a42=(a11*a32);
  a42=(a0*a42);
  a43=(a21*a26);
  a42=(a42+a43);
  a43=(a18*a32);
  a43=(a0*a43);
  a44=(a23*a26);
  a43=(a43+a44);
  a42=(a42+a43);
  a40=(a40-a42);
  a42=casadi_sign(a4);
  a43=(a42*a35);
  a43=(a22*a43);
  a43=(a4*a43);
  a44=(a24*a35);
  a43=(a43+a44);
  a40=(a40+a43);
  a40=(a40/a25);
  if (res[1]!=0) res[1][4]=a40;
  a40=(a18*a26);
  a40=(a4*a40);
  a43=(a20*a35);
  a40=(a40+a43);
  a38=(a27*a38);
  a34=(a28*a34);
  a38=(a38+a34);
  a26=(a13*a26);
  a26=(a4*a26);
  a35=(a9*a35);
  a26=(a26+a35);
  a38=(a38+a26);
  a40=(a40-a38);
  a38=(a8*a32);
  a40=(a40+a38);
  a38=casadi_sign(a6);
  a26=(a38*a32);
  a26=(a29*a26);
  a26=(a6*a26);
  a32=(a30*a32);
  a26=(a26+a32);
  a40=(a40+a26);
  a40=(a40/a31);
  if (res[1]!=0) res[1][5]=a40;
  a40=0.;
  if (res[1]!=0) res[1][6]=a40;
  if (res[1]!=0) res[1][7]=a40;
  a26=arg[1]? arg[1][11] : 0;
  a32=(a2*a26);
  a35=arg[1]? arg[1][10] : 0;
  a34=(a33*a35);
  a34=(a0*a34);
  a32=(a32-a34);
  a34=arg[1]? arg[1][12] : 0;
  a43=(a5*a34);
  a44=(a37*a35);
  a44=(a4*a44);
  a43=(a43+a44);
  a32=(a32-a43);
  if (res[1]!=0) res[1][8]=a32;
  a32=(a3*a26);
  a43=(a36*a35);
  a43=(a0*a43);
  a32=(a32+a43);
  a43=(a7*a34);
  a35=(a39*a35);
  a35=(a4*a35);
  a43=(a43-a35);
  a32=(a32+a43);
  if (res[1]!=0) res[1][9]=a32;
  a32=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a32;
  a43=arg[1]? arg[1][14] : 0;
  a35=arg[1]? arg[1][15] : 0;
  a44=(a43+a35);
  a45=(a11*a32);
  a45=(a4*a45);
  a46=(a12*a34);
  a45=(a45+a46);
  a44=(a44+a45);
  a45=(a13*a32);
  a45=(a4*a45);
  a46=(a14*a34);
  a45=(a45+a46);
  a44=(a44+a45);
  a45=(a15*a26);
  a44=(a44+a45);
  a45=(a41*a26);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a26);
  a45=(a45+a46);
  a44=(a44+a45);
  a44=(a44/a19);
  if (res[1]!=0) res[1][11]=a44;
  a44=(a10*a34);
  a45=(a11*a32);
  a45=(a0*a45);
  a46=(a21*a26);
  a45=(a45+a46);
  a46=(a18*a32);
  a46=(a0*a46);
  a47=(a23*a26);
  a46=(a46+a47);
  a45=(a45+a46);
  a44=(a44-a45);
  a45=(a42*a34);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a34);
  a45=(a45+a46);
  a44=(a44+a45);
  a44=(a44/a25);
  if (res[1]!=0) res[1][12]=a44;
  a44=(a18*a26);
  a44=(a4*a44);
  a45=(a20*a34);
  a44=(a44+a45);
  a43=(a27*a43);
  a35=(a28*a35);
  a43=(a43+a35);
  a26=(a13*a26);
  a26=(a4*a26);
  a34=(a9*a34);
  a26=(a26+a34);
  a43=(a43+a26);
  a44=(a44-a43);
  a43=(a8*a32);
  a44=(a44+a43);
  a43=(a38*a32);
  a43=(a29*a43);
  a43=(a6*a43);
  a32=(a30*a32);
  a43=(a43+a32);
  a44=(a44+a43);
  a44=(a44/a31);
  if (res[1]!=0) res[1][13]=a44;
  if (res[1]!=0) res[1][14]=a40;
  if (res[1]!=0) res[1][15]=a40;
  a44=arg[1]? arg[1][19] : 0;
  a43=(a2*a44);
  a32=arg[1]? arg[1][18] : 0;
  a26=(a33*a32);
  a26=(a0*a26);
  a43=(a43-a26);
  a26=arg[1]? arg[1][20] : 0;
  a34=(a5*a26);
  a35=(a37*a32);
  a35=(a4*a35);
  a34=(a34+a35);
  a43=(a43-a34);
  if (res[1]!=0) res[1][16]=a43;
  a43=(a3*a44);
  a34=(a36*a32);
  a34=(a0*a34);
  a43=(a43+a34);
  a34=(a7*a26);
  a32=(a39*a32);
  a32=(a4*a32);
  a34=(a34-a32);
  a43=(a43+a34);
  if (res[1]!=0) res[1][17]=a43;
  a43=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a43;
  a34=arg[1]? arg[1][22] : 0;
  a32=arg[1]? arg[1][23] : 0;
  a35=(a34+a32);
  a45=(a11*a43);
  a45=(a4*a45);
  a46=(a12*a26);
  a45=(a45+a46);
  a35=(a35+a45);
  a45=(a13*a43);
  a45=(a4*a45);
  a46=(a14*a26);
  a45=(a45+a46);
  a35=(a35+a45);
  a45=(a15*a44);
  a35=(a35+a45);
  a45=(a41*a44);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a44);
  a45=(a45+a46);
  a35=(a35+a45);
  a35=(a35/a19);
  if (res[1]!=0) res[1][19]=a35;
  a35=(a10*a26);
  a45=(a11*a43);
  a45=(a0*a45);
  a46=(a21*a44);
  a45=(a45+a46);
  a46=(a18*a43);
  a46=(a0*a46);
  a47=(a23*a44);
  a46=(a46+a47);
  a45=(a45+a46);
  a35=(a35-a45);
  a45=(a42*a26);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a26);
  a45=(a45+a46);
  a35=(a35+a45);
  a35=(a35/a25);
  if (res[1]!=0) res[1][20]=a35;
  a35=(a18*a44);
  a35=(a4*a35);
  a45=(a20*a26);
  a35=(a35+a45);
  a34=(a27*a34);
  a32=(a28*a32);
  a34=(a34+a32);
  a44=(a13*a44);
  a44=(a4*a44);
  a26=(a9*a26);
  a44=(a44+a26);
  a34=(a34+a44);
  a35=(a35-a34);
  a34=(a8*a43);
  a35=(a35+a34);
  a34=(a38*a43);
  a34=(a29*a34);
  a34=(a6*a34);
  a43=(a30*a43);
  a34=(a34+a43);
  a35=(a35+a34);
  a35=(a35/a31);
  if (res[1]!=0) res[1][21]=a35;
  if (res[1]!=0) res[1][22]=a40;
  if (res[1]!=0) res[1][23]=a40;
  a35=arg[1]? arg[1][27] : 0;
  a34=(a2*a35);
  a43=arg[1]? arg[1][26] : 0;
  a44=(a33*a43);
  a44=(a0*a44);
  a34=(a34-a44);
  a44=arg[1]? arg[1][28] : 0;
  a26=(a5*a44);
  a32=(a37*a43);
  a32=(a4*a32);
  a26=(a26+a32);
  a34=(a34-a26);
  if (res[1]!=0) res[1][24]=a34;
  a34=(a3*a35);
  a26=(a36*a43);
  a26=(a0*a26);
  a34=(a34+a26);
  a26=(a7*a44);
  a43=(a39*a43);
  a43=(a4*a43);
  a26=(a26-a43);
  a34=(a34+a26);
  if (res[1]!=0) res[1][25]=a34;
  a34=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a34;
  a26=arg[1]? arg[1][30] : 0;
  a43=arg[1]? arg[1][31] : 0;
  a32=(a26+a43);
  a45=(a11*a34);
  a45=(a4*a45);
  a46=(a12*a44);
  a45=(a45+a46);
  a32=(a32+a45);
  a45=(a13*a34);
  a45=(a4*a45);
  a46=(a14*a44);
  a45=(a45+a46);
  a32=(a32+a45);
  a45=(a15*a35);
  a32=(a32+a45);
  a45=(a41*a35);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a35);
  a45=(a45+a46);
  a32=(a32+a45);
  a32=(a32/a19);
  if (res[1]!=0) res[1][27]=a32;
  a32=(a10*a44);
  a45=(a11*a34);
  a45=(a0*a45);
  a46=(a21*a35);
  a45=(a45+a46);
  a46=(a18*a34);
  a46=(a0*a46);
  a47=(a23*a35);
  a46=(a46+a47);
  a45=(a45+a46);
  a32=(a32-a45);
  a45=(a42*a44);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a44);
  a45=(a45+a46);
  a32=(a32+a45);
  a32=(a32/a25);
  if (res[1]!=0) res[1][28]=a32;
  a32=(a18*a35);
  a32=(a4*a32);
  a45=(a20*a44);
  a32=(a32+a45);
  a26=(a27*a26);
  a43=(a28*a43);
  a26=(a26+a43);
  a35=(a13*a35);
  a35=(a4*a35);
  a44=(a9*a44);
  a35=(a35+a44);
  a26=(a26+a35);
  a32=(a32-a26);
  a26=(a8*a34);
  a32=(a32+a26);
  a26=(a38*a34);
  a26=(a29*a26);
  a26=(a6*a26);
  a34=(a30*a34);
  a26=(a26+a34);
  a32=(a32+a26);
  a32=(a32/a31);
  if (res[1]!=0) res[1][29]=a32;
  if (res[1]!=0) res[1][30]=a40;
  if (res[1]!=0) res[1][31]=a40;
  a32=arg[1]? arg[1][35] : 0;
  a26=(a2*a32);
  a34=arg[1]? arg[1][34] : 0;
  a35=(a33*a34);
  a35=(a0*a35);
  a26=(a26-a35);
  a35=arg[1]? arg[1][36] : 0;
  a44=(a5*a35);
  a43=(a37*a34);
  a43=(a4*a43);
  a44=(a44+a43);
  a26=(a26-a44);
  if (res[1]!=0) res[1][32]=a26;
  a26=(a3*a32);
  a44=(a36*a34);
  a44=(a0*a44);
  a26=(a26+a44);
  a44=(a7*a35);
  a34=(a39*a34);
  a34=(a4*a34);
  a44=(a44-a34);
  a26=(a26+a44);
  if (res[1]!=0) res[1][33]=a26;
  a26=arg[1]? arg[1][37] : 0;
  if (res[1]!=0) res[1][34]=a26;
  a44=arg[1]? arg[1][38] : 0;
  a34=arg[1]? arg[1][39] : 0;
  a43=(a44+a34);
  a45=(a11*a26);
  a45=(a4*a45);
  a46=(a12*a35);
  a45=(a45+a46);
  a43=(a43+a45);
  a45=(a13*a26);
  a45=(a4*a45);
  a46=(a14*a35);
  a45=(a45+a46);
  a43=(a43+a45);
  a45=(a15*a32);
  a43=(a43+a45);
  a45=(a41*a32);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a32);
  a45=(a45+a46);
  a43=(a43+a45);
  a43=(a43/a19);
  if (res[1]!=0) res[1][35]=a43;
  a43=(a10*a35);
  a45=(a11*a26);
  a45=(a0*a45);
  a46=(a21*a32);
  a45=(a45+a46);
  a46=(a18*a26);
  a46=(a0*a46);
  a47=(a23*a32);
  a46=(a46+a47);
  a45=(a45+a46);
  a43=(a43-a45);
  a45=(a42*a35);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a35);
  a45=(a45+a46);
  a43=(a43+a45);
  a43=(a43/a25);
  if (res[1]!=0) res[1][36]=a43;
  a43=(a18*a32);
  a43=(a4*a43);
  a45=(a20*a35);
  a43=(a43+a45);
  a44=(a27*a44);
  a34=(a28*a34);
  a44=(a44+a34);
  a32=(a13*a32);
  a32=(a4*a32);
  a35=(a9*a35);
  a32=(a32+a35);
  a44=(a44+a32);
  a43=(a43-a44);
  a44=(a8*a26);
  a43=(a43+a44);
  a44=(a38*a26);
  a44=(a29*a44);
  a44=(a6*a44);
  a26=(a30*a26);
  a44=(a44+a26);
  a43=(a43+a44);
  a43=(a43/a31);
  if (res[1]!=0) res[1][37]=a43;
  if (res[1]!=0) res[1][38]=a40;
  if (res[1]!=0) res[1][39]=a40;
  a43=arg[1]? arg[1][43] : 0;
  a44=(a2*a43);
  a26=arg[1]? arg[1][42] : 0;
  a32=(a33*a26);
  a32=(a0*a32);
  a44=(a44-a32);
  a32=arg[1]? arg[1][44] : 0;
  a35=(a5*a32);
  a34=(a37*a26);
  a34=(a4*a34);
  a35=(a35+a34);
  a44=(a44-a35);
  if (res[1]!=0) res[1][40]=a44;
  a44=(a3*a43);
  a35=(a36*a26);
  a35=(a0*a35);
  a44=(a44+a35);
  a35=(a7*a32);
  a26=(a39*a26);
  a26=(a4*a26);
  a35=(a35-a26);
  a44=(a44+a35);
  if (res[1]!=0) res[1][41]=a44;
  a44=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][42]=a44;
  a35=arg[1]? arg[1][46] : 0;
  a26=arg[1]? arg[1][47] : 0;
  a34=(a35+a26);
  a45=(a11*a44);
  a45=(a4*a45);
  a46=(a12*a32);
  a45=(a45+a46);
  a34=(a34+a45);
  a45=(a13*a44);
  a45=(a4*a45);
  a46=(a14*a32);
  a45=(a45+a46);
  a34=(a34+a45);
  a45=(a15*a43);
  a34=(a34+a45);
  a45=(a41*a43);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a43);
  a45=(a45+a46);
  a34=(a34+a45);
  a34=(a34/a19);
  if (res[1]!=0) res[1][43]=a34;
  a34=(a10*a32);
  a45=(a11*a44);
  a45=(a0*a45);
  a46=(a21*a43);
  a45=(a45+a46);
  a46=(a18*a44);
  a46=(a0*a46);
  a47=(a23*a43);
  a46=(a46+a47);
  a45=(a45+a46);
  a34=(a34-a45);
  a45=(a42*a32);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a32);
  a45=(a45+a46);
  a34=(a34+a45);
  a34=(a34/a25);
  if (res[1]!=0) res[1][44]=a34;
  a34=(a18*a43);
  a34=(a4*a34);
  a45=(a20*a32);
  a34=(a34+a45);
  a35=(a27*a35);
  a26=(a28*a26);
  a35=(a35+a26);
  a43=(a13*a43);
  a43=(a4*a43);
  a32=(a9*a32);
  a43=(a43+a32);
  a35=(a35+a43);
  a34=(a34-a35);
  a35=(a8*a44);
  a34=(a34+a35);
  a35=(a38*a44);
  a35=(a29*a35);
  a35=(a6*a35);
  a44=(a30*a44);
  a35=(a35+a44);
  a34=(a34+a35);
  a34=(a34/a31);
  if (res[1]!=0) res[1][45]=a34;
  if (res[1]!=0) res[1][46]=a40;
  if (res[1]!=0) res[1][47]=a40;
  a34=arg[1]? arg[1][51] : 0;
  a35=(a2*a34);
  a44=arg[1]? arg[1][50] : 0;
  a43=(a33*a44);
  a43=(a0*a43);
  a35=(a35-a43);
  a43=arg[1]? arg[1][52] : 0;
  a32=(a5*a43);
  a26=(a37*a44);
  a26=(a4*a26);
  a32=(a32+a26);
  a35=(a35-a32);
  if (res[1]!=0) res[1][48]=a35;
  a35=(a3*a34);
  a32=(a36*a44);
  a32=(a0*a32);
  a35=(a35+a32);
  a32=(a7*a43);
  a44=(a39*a44);
  a44=(a4*a44);
  a32=(a32-a44);
  a35=(a35+a32);
  if (res[1]!=0) res[1][49]=a35;
  a35=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][50]=a35;
  a32=arg[1]? arg[1][54] : 0;
  a44=arg[1]? arg[1][55] : 0;
  a26=(a32+a44);
  a45=(a11*a35);
  a45=(a4*a45);
  a46=(a12*a43);
  a45=(a45+a46);
  a26=(a26+a45);
  a45=(a13*a35);
  a45=(a4*a45);
  a46=(a14*a43);
  a45=(a45+a46);
  a26=(a26+a45);
  a45=(a15*a34);
  a26=(a26+a45);
  a45=(a41*a34);
  a45=(a16*a45);
  a45=(a0*a45);
  a46=(a17*a34);
  a45=(a45+a46);
  a26=(a26+a45);
  a26=(a26/a19);
  if (res[1]!=0) res[1][51]=a26;
  a26=(a10*a43);
  a45=(a11*a35);
  a45=(a0*a45);
  a46=(a21*a34);
  a45=(a45+a46);
  a46=(a18*a35);
  a46=(a0*a46);
  a47=(a23*a34);
  a46=(a46+a47);
  a45=(a45+a46);
  a26=(a26-a45);
  a45=(a42*a43);
  a45=(a22*a45);
  a45=(a4*a45);
  a46=(a24*a43);
  a45=(a45+a46);
  a26=(a26+a45);
  a26=(a26/a25);
  if (res[1]!=0) res[1][52]=a26;
  a26=(a18*a34);
  a26=(a4*a26);
  a45=(a20*a43);
  a26=(a26+a45);
  a32=(a27*a32);
  a44=(a28*a44);
  a32=(a32+a44);
  a34=(a13*a34);
  a34=(a4*a34);
  a43=(a9*a43);
  a34=(a34+a43);
  a32=(a32+a34);
  a26=(a26-a32);
  a32=(a8*a35);
  a26=(a26+a32);
  a32=(a38*a35);
  a32=(a29*a32);
  a32=(a6*a32);
  a35=(a30*a35);
  a32=(a32+a35);
  a26=(a26+a32);
  a26=(a26/a31);
  if (res[1]!=0) res[1][53]=a26;
  if (res[1]!=0) res[1][54]=a40;
  if (res[1]!=0) res[1][55]=a40;
  a26=arg[1]? arg[1][59] : 0;
  a32=(a2*a26);
  a35=arg[1]? arg[1][58] : 0;
  a33=(a33*a35);
  a33=(a0*a33);
  a32=(a32-a33);
  a33=arg[1]? arg[1][60] : 0;
  a34=(a5*a33);
  a37=(a37*a35);
  a37=(a4*a37);
  a34=(a34+a37);
  a32=(a32-a34);
  if (res[1]!=0) res[1][56]=a32;
  a32=(a3*a26);
  a36=(a36*a35);
  a36=(a0*a36);
  a32=(a32+a36);
  a36=(a7*a33);
  a39=(a39*a35);
  a39=(a4*a39);
  a36=(a36-a39);
  a32=(a32+a36);
  if (res[1]!=0) res[1][57]=a32;
  a32=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][58]=a32;
  a36=arg[1]? arg[1][62] : 0;
  a39=arg[1]? arg[1][63] : 0;
  a35=(a36+a39);
  a34=(a11*a32);
  a34=(a4*a34);
  a37=(a12*a33);
  a34=(a34+a37);
  a35=(a35+a34);
  a34=(a13*a32);
  a34=(a4*a34);
  a37=(a14*a33);
  a34=(a34+a37);
  a35=(a35+a34);
  a34=(a15*a26);
  a35=(a35+a34);
  a41=(a41*a26);
  a41=(a16*a41);
  a41=(a0*a41);
  a34=(a17*a26);
  a41=(a41+a34);
  a35=(a35+a41);
  a35=(a35/a19);
  if (res[1]!=0) res[1][59]=a35;
  a35=(a10*a33);
  a41=(a11*a32);
  a41=(a0*a41);
  a34=(a21*a26);
  a41=(a41+a34);
  a34=(a18*a32);
  a34=(a0*a34);
  a37=(a23*a26);
  a34=(a34+a37);
  a41=(a41+a34);
  a35=(a35-a41);
  a42=(a42*a33);
  a42=(a22*a42);
  a42=(a4*a42);
  a41=(a24*a33);
  a42=(a42+a41);
  a35=(a35+a42);
  a35=(a35/a25);
  if (res[1]!=0) res[1][60]=a35;
  a35=(a18*a26);
  a35=(a4*a35);
  a42=(a20*a33);
  a35=(a35+a42);
  a36=(a27*a36);
  a39=(a28*a39);
  a36=(a36+a39);
  a26=(a13*a26);
  a26=(a4*a26);
  a33=(a9*a33);
  a26=(a26+a33);
  a36=(a36+a26);
  a35=(a35-a36);
  a36=(a8*a32);
  a35=(a35+a36);
  a38=(a38*a32);
  a38=(a29*a38);
  a38=(a6*a38);
  a32=(a30*a32);
  a38=(a38+a32);
  a35=(a35+a38);
  a35=(a35/a31);
  if (res[1]!=0) res[1][61]=a35;
  if (res[1]!=0) res[1][62]=a40;
  if (res[1]!=0) res[1][63]=a40;
  a35=arg[2]? arg[2][3] : 0;
  a38=(a2*a35);
  a32=sin(a1);
  a36=arg[2]? arg[2][2] : 0;
  a26=(a32*a36);
  a26=(a0*a26);
  a38=(a38-a26);
  a26=arg[2]? arg[2][4] : 0;
  a33=(a5*a26);
  a39=cos(a1);
  a42=(a39*a36);
  a42=(a4*a42);
  a33=(a33+a42);
  a38=(a38-a33);
  if (res[2]!=0) res[2][0]=a38;
  a38=(a3*a35);
  a33=cos(a1);
  a42=(a33*a36);
  a42=(a0*a42);
  a38=(a38+a42);
  a42=(a7*a26);
  a1=sin(a1);
  a36=(a1*a36);
  a36=(a4*a36);
  a42=(a42-a36);
  a38=(a38+a42);
  if (res[2]!=0) res[2][1]=a38;
  a38=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a38;
  a42=arg[2]? arg[2][6] : 0;
  a36=arg[2]? arg[2][7] : 0;
  a41=(a42+a36);
  a34=(a11*a38);
  a34=(a4*a34);
  a37=(a12*a26);
  a34=(a34+a37);
  a41=(a41+a34);
  a34=(a13*a38);
  a34=(a4*a34);
  a37=(a14*a26);
  a34=(a34+a37);
  a41=(a41+a34);
  a34=(a15*a35);
  a41=(a41+a34);
  a34=casadi_sign(a0);
  a37=(a34*a35);
  a37=(a16*a37);
  a37=(a0*a37);
  a43=(a17*a35);
  a37=(a37+a43);
  a41=(a41+a37);
  a41=(a41/a19);
  if (res[2]!=0) res[2][3]=a41;
  a41=(a10*a26);
  a37=(a11*a38);
  a37=(a0*a37);
  a43=(a21*a35);
  a37=(a37+a43);
  a43=(a18*a38);
  a43=(a0*a43);
  a44=(a23*a35);
  a43=(a43+a44);
  a37=(a37+a43);
  a41=(a41-a37);
  a37=casadi_sign(a4);
  a43=(a37*a26);
  a43=(a22*a43);
  a43=(a4*a43);
  a44=(a24*a26);
  a43=(a43+a44);
  a41=(a41+a43);
  a41=(a41/a25);
  if (res[2]!=0) res[2][4]=a41;
  a41=(a18*a35);
  a41=(a4*a41);
  a43=(a20*a26);
  a41=(a41+a43);
  a42=(a27*a42);
  a36=(a28*a36);
  a42=(a42+a36);
  a35=(a13*a35);
  a35=(a4*a35);
  a26=(a9*a26);
  a35=(a35+a26);
  a42=(a42+a35);
  a41=(a41-a42);
  a42=(a8*a38);
  a41=(a41+a42);
  a42=casadi_sign(a6);
  a35=(a42*a38);
  a35=(a29*a35);
  a35=(a6*a35);
  a38=(a30*a38);
  a35=(a35+a38);
  a41=(a41+a35);
  a41=(a41/a31);
  if (res[2]!=0) res[2][5]=a41;
  a41=1.;
  if (res[2]!=0) res[2][6]=a41;
  if (res[2]!=0) res[2][7]=a40;
  a35=arg[2]? arg[2][11] : 0;
  a2=(a2*a35);
  a38=arg[2]? arg[2][10] : 0;
  a32=(a32*a38);
  a32=(a0*a32);
  a2=(a2-a32);
  a32=arg[2]? arg[2][12] : 0;
  a5=(a5*a32);
  a39=(a39*a38);
  a39=(a4*a39);
  a5=(a5+a39);
  a2=(a2-a5);
  if (res[2]!=0) res[2][8]=a2;
  a3=(a3*a35);
  a33=(a33*a38);
  a33=(a0*a33);
  a3=(a3+a33);
  a7=(a7*a32);
  a1=(a1*a38);
  a1=(a4*a1);
  a7=(a7-a1);
  a3=(a3+a7);
  if (res[2]!=0) res[2][9]=a3;
  a3=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a3;
  a7=arg[2]? arg[2][14] : 0;
  a1=arg[2]? arg[2][15] : 0;
  a38=(a7+a1);
  a33=(a11*a3);
  a33=(a4*a33);
  a12=(a12*a32);
  a33=(a33+a12);
  a38=(a38+a33);
  a33=(a13*a3);
  a33=(a4*a33);
  a14=(a14*a32);
  a33=(a33+a14);
  a38=(a38+a33);
  a15=(a15*a35);
  a38=(a38+a15);
  a34=(a34*a35);
  a16=(a16*a34);
  a16=(a0*a16);
  a17=(a17*a35);
  a16=(a16+a17);
  a38=(a38+a16);
  a38=(a38/a19);
  if (res[2]!=0) res[2][11]=a38;
  a10=(a10*a32);
  a11=(a11*a3);
  a11=(a0*a11);
  a21=(a21*a35);
  a11=(a11+a21);
  a21=(a18*a3);
  a0=(a0*a21);
  a23=(a23*a35);
  a0=(a0+a23);
  a11=(a11+a0);
  a10=(a10-a11);
  a37=(a37*a32);
  a22=(a22*a37);
  a22=(a4*a22);
  a24=(a24*a32);
  a22=(a22+a24);
  a10=(a10+a22);
  a10=(a10/a25);
  if (res[2]!=0) res[2][12]=a10;
  a18=(a18*a35);
  a18=(a4*a18);
  a20=(a20*a32);
  a18=(a18+a20);
  a27=(a27*a7);
  a28=(a28*a1);
  a27=(a27+a28);
  a13=(a13*a35);
  a4=(a4*a13);
  a9=(a9*a32);
  a4=(a4+a9);
  a27=(a27+a4);
  a18=(a18-a27);
  a8=(a8*a3);
  a18=(a18+a8);
  a42=(a42*a3);
  a29=(a29*a42);
  a6=(a6*a29);
  a30=(a30*a3);
  a6=(a6+a30);
  a18=(a18+a6);
  a18=(a18/a31);
  if (res[2]!=0) res[2][13]=a18;
  if (res[2]!=0) res[2][14]=a40;
  if (res[2]!=0) res[2][15]=a41;
  return 0;
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void shark_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void shark_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void shark_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void shark_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int shark_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int shark_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real shark_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* shark_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* shark_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* shark_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* shark_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int shark_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
